<a href="https://colab.research.google.com/github/Shota-8811396/output/blob/main/Python%E3%81%A7%E5%AE%9F%E8%A3%85%EF%BC%91.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

|$n$|$x_{n}$|$t_{n}$|
|:--|:--|:--|
|1|20|60000|
|2|40|115000|
|3|60|155000|

In [ ]:
x = np.array([20,40,60])
x

array([20, 40, 60])

In [ ]:
type(x)

numpy.ndarray

In [ ]:
t = np.array([60000,115000,155000])
t

array([ 60000, 115000, 155000])

In [ ]:
x_mean = x.mean()
x_mean

40.0

In [ ]:
t_mean = t.mean()
t_mean

110000.0

In [ ]:
# xの中心化
xc = x - x_mean
xc

array([-20.,   0.,  20.])

In [ ]:
# tの中心化
tc = t - t_mean
tc

array([-50000.,   5000.,  45000.])

最適なパラメータ

$$
w = \dfrac{\sum_{n=1}^{N} x_{n}t_{n}}{\sum_{n=1}^{N} x_{n}^{2}}
$$

を求める。

まずは分子

$$
\sum_{n=1}^{N} x_{n}t_{n}
$$

を求める。

In [ ]:
# 要素ごとの積
xc * tc

array([1000000.,       0.,  900000.])

In [ ]:
# 要素ごとの積の総和
(xc * tc).sum()

1900000.0

分母

$$
\sum_{n=1}^{N} x_{n}^{2}
$$

を求める。

In [ ]:
xc * xc

array([400.,   0., 400.])

In [ ]:
(xc * xc).sum()

800.0

In [ ]:
# 最適なパラメータ
w = (xc * tc).sum() / (xc * xc).sum()
w

2375.0

このパラメータを用いて、$x=50$の場合の予測値$y$を求める。

$$
\begin{aligned}
y_{c} &= w x_{c} \\
y - \bar{t} &= w (x-\bar{x}) \\
y &= w (x - \bar{x}) + \bar{t}
\end{aligned}
$$

In [ ]:
x = 50

In [ ]:
y = w * (x - x_mean) + t_mean
y

133750.0