<a href="https://colab.research.google.com/github/Shota-8811396/output/blob/output/%E3%83%8B%E3%83%A5%E3%83%BC%E3%83%A9%E3%83%AB%E3%83%8D%E3%83%83%E3%83%88%E3%83%AF%E3%83%BC%E3%82%AF%E5%AE%9F%E8%A3%85%E2%91%A0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### ネットワークの定義と順伝播の計算

#### 1.環境構築

In [ ]:
import torch

In [ ]:
torch.__version__

'2.0.1+cu118'

#### 2.ネットワークの定義

In [ ]:
import torch.nn as nn

In [ ]:
# 3ノード　→ ２ノードの全結合（fully-connected layer)
fc = nn.Linear(3, 2)
fc

Linear(in_features=3, out_features=2, bias=True)

In [ ]:
# 重み
fc.weight

Parameter containing:
tensor([[ 0.1602, -0.1098, -0.0108],
        [-0.1178, -0.4985, -0.1584]], requires_grad=True)

In [ ]:
# バイアス
fc.bias

Parameter containing:
tensor([-0.0989, -0.5710], requires_grad=True)

In [ ]:
# 乱数のシードを固定
torch.manual_seed(0)

In [ ]:
fc = nn.Linear(3,2)

In [ ]:
fc.weight

Parameter containing:
tensor([[-0.0043,  0.3097, -0.4752],
        [-0.4249, -0.2224,  0.1548]], requires_grad=True)

In [ ]:
fc.bias

Parameter containing:
tensor([-0.0114,  0.4578], requires_grad=True)

#### 3.線形変換

In [ ]:
fc

Linear(in_features=3, out_features=2, bias=True)

In [ ]:
x = torch.Tensor([1., 2., 3.])
x

tensor([1., 2., 3.])

In [ ]:
type(x)

torch.Tensor

In [ ]:
x.dtype

torch.float32

In [ ]:
x.shape

torch.Size([3])

In [ ]:
# 線形変換
# fc.__call__(x) ←これでも書ける
u = fc(x)
u

tensor([-0.8219,  0.0526], grad_fn=<AddBackward0>)

#### 4.非線形変換

In [ ]:
import torch.nn.functional as F

In [ ]:
h = F.relu(u)
h

tensor([0.0000, 0.0526], grad_fn=<ReluBackward0>)

#### 5.目的関数

目的関数 = 損失関数 + 正則化項

In [ ]:
# 目標値
t = torch.Tensor([[1], [3]])
t

tensor([[1.],
        [3.]])

In [ ]:
# 予測値
y = torch.Tensor([[2], [4]])
y

tensor([[2.],
        [4.]])

In [ ]:
# 平均二乗誤差
F.mse_loss(y, t)

tensor(1.)

#### 6. nn と F の使い分け

- nn : torch.nn → パラメータを持つ場合
- F : torch.nn.functional → パラメータを持たない場合