<a href="https://colab.research.google.com/github/Shota-8811396/output/blob/output/%E6%95%B0%E5%AD%A6%E3%81%AE%E5%9F%BA%E7%A4%8E%E2%91%A1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

重回帰分析によってもとまる最適なパラメータ

$$
{\bf w} = ({\bf X}^{\rm T}{\bf X})^{-1}{\bf X}^{\rm T}{\bf t}
$$

In [1]:
import numpy as np

In [2]:
np.__version__

'1.22.4'

- ベクトルの定義
- 行列の定義
- 転置
- 行列積
- 逆行列

$$
{\bf X} =
\begin{bmatrix}
1 & 3 \\
2 & 4 \\
5 & 6 
\end{bmatrix}, \
{\bf t} =
\begin{bmatrix}
1 \\ 2 \\ 7
\end {bmatrix}
$$

上記のデータセットは以下の関係性から生成

$$
y = 3x_{1} - 2x_{2} + 4
$$

理想的にはパラメータが以下のようにもとまると望ましい。

$$
w_{1} = 3, \ w_{2}=-2, \ b=4
$$

In [3]:
# ベクトルの定義
t = np.array([[1], [2],[7]])
print(t)

[[1]
 [2]
 [7]]


In [4]:
# 行列の定義
X = np.array([
    [1, 3],
    [2, 4],
    [5, 6]
])

print(X)

[[1 3]
 [2 4]
 [5 6]]


In [5]:
# ベクトル t のサイズを確認
t.shape

(3, 1)

In [6]:
# 行列 X のサイズを確認
X.shape

(3, 2)

In [7]:
# 全ての要素が 1 のベクトル
ones = np.ones((3, 1))
print(ones)

[[1.]
 [1.]
 [1.]]


In [8]:
# 要素が全て １ のベクトルと行列 X の結合
X = np.concatenate((ones, X), axis=1)
print(X)

[[1. 1. 3.]
 [1. 2. 4.]
 [1. 5. 6.]]


In [9]:
# 転置
print(X.T)

[[1. 1. 1.]
 [1. 2. 5.]
 [3. 4. 6.]]


$$
{\bf X}^{\rm T}{\bf X}
$$

In [10]:
# 行列積
XX = np.dot(X.T, X)
print(XX)

[[ 3.  8. 13.]
 [ 8. 30. 41.]
 [13. 41. 61.]]


$$
({\bf X}^{\rm T}{\bf X})^{-1}
$$

In [11]:
# 逆行列
XX_inv = np.linalg.inv(XX)
print(XX_inv)

[[149.  45. -62.]
 [ 45.  14. -19.]
 [-62. -19.  26.]]


$$
{\bf w} = ({\bf X}^{\rm T}{\bf X})^{-1}{\bf X}^{\rm T}{\bf t}
$$

In [12]:
# Xtの計算
Xt = np.dot(X.T, t)
print(Xt)

[[10.]
 [40.]
 [53.]]


In [14]:
# パラメータwを求める
w = np.dot(XX_inv, Xt)
print(w)

[[ 4.]
 [ 3.]
 [-2.]]
